/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysLakeRoomRouteImport } from './routes/stays.lake-room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaysRoute,
} as any)
const StaysLakeRoomRoute = StaysLakeRoomRouteImport.update({
  id: '/lake-room',
  path: '/lake-room',
  getParentRoute: () => StaysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/stays': typeof StaysRouteWithChildren
  '/stays/lake-room': typeof StaysLakeRoomRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/stays/lake-room': typeof StaysLakeRoomRoute
  '/stays': typeof StaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/stays': typeof StaysRouteWithChildren
  '/stays/lake-room': typeof StaysLakeRoomRoute
  '/stays/': typeof StaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/field-notes' | '/stays' | '/stays/lake-room' | '/stays/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/field-notes' | '/stays/lake-room' | '/stays'
  id:
    | '__root__'
    | '/'
    | '/field-notes'
    | '/stays'
    | '/stays/lake-room'
    | '/stays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FieldNotesRoute: typeof FieldNotesRoute
  StaysRoute: typeof StaysRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/lake-room': {
      id: '/stays/lake-room'
      path: '/lake-room'
      fullPath: '/stays/lake-room'
      preLoaderRoute: typeof StaysLakeRoomRouteImport
      parentRoute: typeof StaysRoute
    }
  }
}

interface StaysRouteChildren {
  StaysLakeRoomRoute: typeof StaysLakeRoomRoute
  StaysIndexRoute: typeof StaysIndexRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysLakeRoomRoute: StaysLakeRoomRoute,
  StaysIndexRoute: StaysIndexRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FieldNotesRoute: FieldNotesRoute,
  StaysRoute: StaysRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()


